# tomcat port
server:
  port: 8080
  servlet:
    session:
      timeout: 3600

spring:
  # MySQL DB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?allowMultiQueries=true&useSSL=false
    username: blog
    password: 123123

    # Hikari Pool
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123123

  # RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: blog
    password: 123123
    virtual-host: blog

  # Mail
  mail:
    protocol: smtp
    host: smtp.qq.com
    username: 23333333
    password: 23333333
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          startttls:
            enabled: true
            required: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
              fallback: false

  # Multipart File
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

# ES
elasticsearch:
  host: 127.0.0.1
  port: 9200
  username: blog
  password: 123123
  connectTimeOut: 10000
  socketTimeOut: 10000
  connectionRequestTimeOut: 10000
  maxConnTotal: 100
  maxConnPerRoute: 100

# MybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# ftp
ftp:
  hostname: "127.0.0.1"
  port: 21
  address: "http://127.0.0.1/static/"
  username: "blog"
  password: "123123"

# baidu map
baidu:
  url: "http://api.map.baidu.com/location/ip"
  ak: "23333333"
  coor: "23333333"

# qq
qq:
  app-id: "23333333"
  user-info-url: "https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}"
